### ISSUE TITLE
关于汽车之家签到

### ISSUE THREAD

**Issue by warlock-lv** [bighammer-link/Common-scripts#1]
我用了你的脚本，换成自己的cookie，好用，可以签到。
但是在这之前 我也写过其它论坛的签到
我用的是如下代码达到cookie登陆的目的。
但是我发现这种方式 用在汽车之家 登录不了。
我搞不明白 什么原因。我不是专职爬虫开发。
你看看 你能知道原因吗？   
       cookie = ''
        dd = SimpleCookie(cookie)
        xx = {v.key: v.value for k, v in dd.items()}

        self.driver.get('https://i.autohome.com.cn/')
        for kk, vv in xx.items():
            self.driver.add_cookie(cookie_dict={'name': kk, 'value': vv})
        self.driver.refresh()

**Comment by bighammer-link** [comment]
> 

我也不是很清楚，你可以参考以下这个文章 https://www.cnblogs.com/whz0215/p/9676676.html

**Comment by bighammer-link** [comment]
> 我用了你的脚本，换成自己的cookie，好用，可以签到。 但是在这之前 我也写过其它论坛的签到 我用的是如下代码达到cookie登陆的目的。 但是我发现这种方式 用在汽车之家 登录不了。 我搞不明白 什么原因。我不是专职爬虫开发。 你看看 你能知道原因吗？ cookie = '' dd = SimpleCookie(cookie) xx = {v.key: v.value for k, v in dd.items()}
> 
> ```
>     self.driver.get('https://i.autohome.com.cn/')
>     for kk, vv in xx.items():
>         self.driver.add_cookie(cookie_dict={'name': kk, 'value': vv})
>     self.driver.refresh()
> ```

我也不是很清楚，你可以参考以下这个文章 https://www.cnblogs.com/whz0215/p/9676676.html

**Comment by warlock-lv** [comment]
用你的脚本，那个cookie会过期，要怎么办？那个cookie里可能有一些关键数据是要变化的？

**Comment by bighammer-link** [comment]
> 用你的脚本，那个cookie会过期，要怎么办？那个cookie里可能有一些关键数据是要变化的？

对的，这个cookie会过期，只会持续一段时间，要定时更新，抓取cookie最好使用浏览器无痕模式抓取

**Comment by bighammer-link** [comment]
> 用你的脚本，那个cookie会过期，要怎么办？那个cookie里可能有一些关键数据是要变化的？

因为，汽车之家登录有滑块验证，使用cookie就是跳过滑过验证这个麻烦
